### ISSUE TITLE
Create action to rebuild preview branch from scratch

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#951] opened 2021-07-13 00:17 UTC
We need a straightforward way for any of the editorial team to be able to delete preview and rebuild it.  It should have a workflow_dispatch trigger.

**Comment by bartlettroscoe** [comment] 2021-07-13 16:05
@bernhold, this is a duplicate of #856.

**Closed by bartlettroscoe** 2021-07-13 16:05 UTC
Labels: scope: site-internal
