### ISSUE TITLE
Issues with wikize_refs.py and existing <base>-wikized.md files

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#779] opened 2021-04-01 02:28 UTC
@markcmiller86,

There appears to be some issues running the updated `wikized_refs.py` tool on the existing `<base>-wikized.md` files in the bssw.io repo, I am getting errors.  The files that I am trying to run this on are:

```
[rabartl@crf450 bssw.io (master)]$ find . -name "*-wikized.md" | grep -v ReferencesInMarkdown
./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart2-wikized.md
./Articles/Blog/Covid19WorkstationCleanliness-wikized.md
./Articles/Blog/ApolloGuidanceComputerPart3-wikized.md
./Articles/ShortArticles/PullRequestSizeConsiderations-wikized.md
```

I am getting error output like:

```
$ ./wikized_refs.py -i -w ./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md
Some footnotes never appear in the references...
['24', '26', '27', '20', '21', '16', '33', '32', '31', '13', '35', '36', '12', '4', '8']
Some references never appear in a footnote...
['51', '48', '49', '46', '47', '44', '45', '42', '29', '40', '43', '0', '55', '53', '52', '50']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 302, in build_main_content
    (ref_map[fn[0]][3], ref_map[fn[1]][3]), mcl)
KeyError: '4'
```

The full error output from from all of the runs is given in the detailed output below.

<details>

<summary><b>Detailed error output</b> (Click to expand)</summary>

. 

```
$ for md_file in $(find . -name "*-wikized.md" | grep -v ReferencesInMarkdown) ; do echo ; echo ; echo $md_file ; echo ; ./utils/wikize_refs.py -i -w $md_file ; done


./Articles/Blog/ApolloGuidanceComputerPart1-wikized.md

Some footnotes never appear in the references...
['24', '26', '27', '20', '21', '16', '33', '32', '31', '13', '35', '36', '12', '4', '8']
Some references never appear in a footnote...
['51', '48', '49', '46', '47', '44', '45', '42', '29', '40', '43', '0', '55', '53', '52', '50']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 302, in build_main_content
    (ref_map[fn[0]][3], ref_map[fn[1]][3]), mcl)
KeyError: '4'


./Articles/Blog/ApolloGuidanceComputerPart2-wikized.md

Some footnotes never appear in the references...
['11', '39', '27', '14', '48', '49', '33', '32', '22', '37', '36', '35', '52', '1', '16', '2', '17', '30', '38']
Some references never appear in a footnote...
['59', '58', '0', '55', '54', '57', '56', '53', '60', '61', '62', '65', '66', '67', '68']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 302, in build_main_content
    (ref_map[fn[0]][3], ref_map[fn[1]][3]), mcl)
KeyError: '35'


./Articles/Blog/Covid19WorkstationCleanliness-wikized.md

Some footnotes never appear in the references...
['15', '14', '17', '16', '19', '37', '28', '36', '35', '34', '18']
Some references never appear in a footnote...
['48', '49', '46', '47', '44', '45', '42', '43', '40', '41', '50']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 307, in build_main_content
    (ref_map[fn[0]][3],ref_map[fn[1]][3],ref_map[fn[2]][3]), mcl)
KeyError: '17'


./Articles/Blog/ApolloGuidanceComputerPart3-wikized.md

Some footnotes never appear in the references...
['4']
Some references never appear in a footnote...
['28']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 297, in build_main_content
    mcl = re.sub("<sup>\[%s\]</sup>"%fn, "<pus>[%d]</pus>"%ref_map[fn][3], mcl)
KeyError: '4'


./Articles/ShortArticles/PullRequestSizeConsiderations-wikized.md

Some footnotes never appear in the references...
['8']
Some references never appear in a footnote...
['25', '26']
Traceback (most recent call last):
  File "./utils/wikize_refs.py", line 460, in <module>
    main(opts, mdfile)
  File "./utils/wikize_refs.py", line 431, in main
    out_lines = build_main_content(main_content, ref_map)
  File "./utils/wikize_refs.py", line 307, in build_main_content
    (ref_map[fn[0]][3],ref_map[fn[1]][3],ref_map[fn[2]][3]), mcl)
KeyError: '8'
```

</details>

Any idea what the problem might be?

**Comment by markcmiller86** [comment] 2021-04-01 02:40
I can take a look but probably not until next week.

**Comment by bartlettroscoe** [comment] 2021-04-26 23:25
> I can take a look but probably not until next week.

@markcmiller86, any updates on this?  If not, no big deal.  We can just not bother running `wikize_refs.py` on the existing `*.md` files that are currently broken.  If someone wants to update these files latter, then they can fix the references then.  But we should still delete the defunct source files `<base>.md` and rename `<base>-wikized.md` to `<base>.md` even if  `wikize_refs.py` crashes on those files.  We can just add a comment to the commit log or at the top of those renamed `*.md` files that the file is currently broken for `wikize_refs.py` and needs to be fixed if references are to be changed and run the tool `wikize_refs.py` again.

Does that sound like a good plan to close this issue?

**Comment by markcmiller86** [comment] 2021-04-27 14:09
> @markcmiller86, any updates on this?

Alas, no. Maybe by end of this week.

**Comment by markcmiller86** [comment] 2021-05-12 22:19
I am closing this issue.

The problem is that the tool was run on content (the AGC artcles) that had been wikized with an earlier version (and even along with some hand edits) of that tool. I wouldn't expect it to work on any of the `ApolloGuidanceComputerPartX-wikized.md` files. However, it works fin on their non-wikized counterparts and even cleans them up a bit.

**Comment by bartlettroscoe** [comment] 2021-05-12 23:29
@markcmiller86, one of the goals here is to eliminate the duplicate `<base>.md` and `<base>-wikized.md` files.  So can we just delete all of the remaining `<base>.md` files and rename the existing `<base>-wikize.md` files to `<base>.md`?  The old source `<base>.md` files will still be in the git history if we need them.  That way, people will not be confused by two sets of files `<base>.md` and `<base>-wikized.md`.  Okay?

**Comment by markcmiller86** [comment] 2021-05-12 23:34
Ah, ok. I see. So, there are various manual edits to `-wikized.md` variants after generation. So, my strategy would be the following steps...

- [ ] merge manual edits in `-wikized.md` variants back into base files including bssw.io metadata blocks
- [ ] ensure `wikize_refs.py` runs correctly and reproduces the `-wikized.md` variants correctly.
- [ ] delete the `-wikized.md` variants
- [ ] run `wikize_refs.py` on the base variants *replacing* them.
- [ ] commit the updated base variants
- [ ] confirm all renders fine on preview

Does that sound ok? I think we'll need to do this for a handful (maybe 5-7) files.

**Comment by bartlettroscoe** [comment] 2021-05-12 23:44
> Ah, ok. I see. So, there are various manual edits to `-wikized.md` variants after generation. So, my strategy would be the following steps... ... Does that sound ok? I think we'll need to do this for a handful (maybe 5-7) files.

That sounds like a good plan and it would be ideal.  But if it is unlikely that there will be any more edits to those files or need to run `wikized_refs.py` again on them, then we might just comment at the top of the `<base>-wikized.md` files that they are non-compliant with the current `wikized_ref.py` tool, rename them to `<base>.md` and be done with it.  That would be a lot faster and is likely harmless.  It is just that people just can't use those files as an example of how to use the tool `wikized_ref.py`.

Actually, we need a very simple template for a `<base>.md` file to show how to use the `wikize_refs.py` tool.  I will add a new GitHub Issue for creating an updated set of template `*.md` files for the different types of contributions and we can add a `blog_template_uses_wikized_refs.md` file to this set of new files.

**Closed** 2021-06-19 18:40 UTC
Labels: scope: site-internal, type: bug
